name: nodejs-ci
on:
  workflow_call:
jobs:
  nodejs:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v4
      # Build
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install dependencies
        run: npm ci
      - name: Build 
        run: npm run build --if-present
      # Unit testing
      - name: Test
        run: npm test
      
      # SonarCloud
      # - name: Configure SonarCloud Project
      #   shell: bash
      #   run: |
      #     curl -u ${{ secrets.sonarcloud_token }} --location --request -POST "https://sonarcloud.io/api/projects/create?organizacion=${{ secrets.sonarcloud_org }}&name=${{ env.projectkey }}&project=${{ env.projectkey }}&visibility=private"
      # - name: Sonar
      #   uses: sonarsource/sonarqube-scan-action@master
      #   with:
      #   args: >
      #     -Dsonar.javascript.lcov.reportPaths=./coverage/lcov.info
      #     -Dsonar.projectName=${{ env.projectkey }}
      #     -Dsonar.projectKey=${{ env.projectkey }}
      #   env:
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      #     SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      # # Check the Quality Gate status.
      # - name: SonarQube Quality Gate check
      #   id: sonarqube-quality-gate-check
      #   uses: sonarsource/sonarqube-quality-gate-action@master
      #   # Force to fail step after specific time.
      #   timeout-minutes: 5
      #   env:
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      #     SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      # # The possible outputs of the `quality-gate-status` variable are `PASSED`, `WARN` or `FAILED`.
      # - name: "Show SonarQube Quality Gate Status value"
      #   run: echo "The Quality Gate status is ${{ steps.sonarqube-quality-gate-check.outputs.quality-gate-status }}"
