name: nodejs-ci
on:
  workflow_call:

jobs:
  nodejs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install dependencies
        run: npm ci
      - name: Build 
        run: npm run build --if-present
      - name: Test
        run: ng test
      - name: Build PROJECT_KEY
        env:
          # ORG: ${{ github.event.org.login }}
          ORG: ${{ github.event.actor.login }}
          REPO_NAME: ${{ github.event.repository.name }}
        run: echo "PROJECT_KEY=bescribanobegue_${REPO_NAME}" >> $GITHUB_ENV
      - name: Analyze with SonarCloud
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.javascript.lcov.coverage.reportPaths=./coverage/lcov.info
            -Dsonar.organization=bescribanobegue
            -Dsonar.projectKey=${{ env.PROJECT_KEY }}
      - name: SonarQube Quality Gate check
        id: sonarqube-quality-gate-check
        uses: sonarsource/sonarqube-quality-gate-action@master
        timeout-minutes: 5
        env:
          SONAR_HOST_URL: https://sonarcloud.io/
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
