name: springboot-ci
on:
  workflow_call:
  repository_dispatch:
    types: [backend]
jobs:
  springboot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
            java-version: '17'
            distribution: 'temurin'
            cache: maven
      - name: Build
        run: mvn compile -DskipTests
      - name: Test
        run: mvn test
      - name: Package
        run: mvn package -DskipTests
      # - name: Configure SonarCloud Project
      #   shell: bash
      #   run: |
      #     curl -u ${{ secrets.sonarcloud_token }} --location --request -POST "https://sonarcloud.io/api/projects/create?organizacion=${{ secrets.sonarcloud_org }}&name=${{ env.projectkey }}&project=${{ env.projectkey }}&visibility=private"
      # - name: Sonar
      #   run: mvn sonar:sonar -Dsonar.qualitygate.wait=true
      # - name: Login to Artifactory
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
      #     registry: ${{ARTIFACTORY_REGISTRY}}
      # - name: Build and push
      #   uses: docker/build-push-action@v5
      #   with:
      #     push: true
      #     tags: ${{ REPOSITORY }}/:${{ VERSION }}
      # - name: Deploy with Helm
      #   if: ${{ is_library = true }}
      #   run: helm upgrade --install ${env.APP_NAME} manifests/helm/charts/microservice --values ${env.PROJECT_KEY}/values.yaml -n ${env.PROJECT_KEY} --create-namespace