name: terraform-module-ci
on:
  workflow_call:
jobs:
  springboot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.7.4"
      - name: Checkov GitHub Action
        uses: bridgecrewio/checkov-action@v12
        with:
          output_format: cli
          output_file_path: console
      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
      - name: Terraform Format Check
        run: terraform fmt -check
      - name: Checkov GitHub Action
        uses: bridgecrewio/checkov-action@v12
        with:
          output_format: cli
          output_file_path: console